CREATE DATABASE IF NOT EXISTS jwt_project_db;

USE jwt_project_db;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    age INT UNSIGNED,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- InnoDB: MYSQL의 기본 저장 엔진, REST API 표준.
-- utf8mb4: 4바이트로, 이모지와 다국어 지원.